<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40" 
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9" 
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
    <xsl:template match="/">
        <html xmlns="http://www.w3.org/1999/xhtml">
            <head>
                <title>XML Sitemap - Laboratorium Pemrograman</title>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                <style type="text/css">
                    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size: 14px; color: #333; margin: 0; padding: 20px; background: #f4f7f6; }
                    h1 { color: #2d3748; }
                    table { width: 100%; border-collapse: collapse; background: #fff; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
                    th { background: #4a5568; color: #fff; text-align: left; padding: 12px; }
                    td { padding: 10px; border-bottom: 1px solid #edf2f7; }
                    tr:hover { background: #f7fafc; }
                    a { color: #3182ce; text-decoration: none; }
                    a:hover { text-decoration: underline; }
                    .footer { margin-top: 20px; font-size: 12px; color: #718096; }
                </style>
            </head>
            <body>
                <h1>Sitemap Laboratorium Pemrograman &amp; Komputasi UNTAN</h1>
                <p>Ini adalah daftar halaman yang tersedia untuk publik dan mesin pencari.</p>
                <table>
                    <tr>
                        <th>URL</th>
                        <th>Frekuensi Perubahan</th>
                        <th>Prioritas</th>
                    </tr>
                    <xsl:for-each select="sitemap:urlset/sitemap:url">
                        <tr>
                            <td>
                                <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                            </td>
                            <td><xsl:value-of select="sitemap:changefreq"/></td>
                            <td><xsl:value-of select="sitemap:priority"/></td>
                        </tr>
                    </xsl:for-each>
                </table>
                <div class="footer">
                    Generated by Laravel Sitemap Generator.
                </div>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>